<?php 
// Event Custom Post Type
function tobenski_event_custom_post_type()
{
    $labels = array(
        'name'                     => 'Arrangementer',
        'singular_name'            => 'Arrangement',
        'add_new'                  => 'Tilføj Ny',
        'add_new_item'             => 'Tilføj Nyt Arrangement',
        'edit_item'                => 'Rediger Arrangement',
        'new_item'                 => 'Ny Arrangement',
        'view_item'                => 'Vis Arrangement',
        'view_items'               => 'Vis Arrangementer',
        'search_items'             => 'Søg i Arrangementer',
        'not_found'                => 'Ingen Arrangementer',
        'not_found_in_trash'       => 'Ingen Arrangementer i Papirkurv',
        'parent_item_colon'        => 'Parent Page:',
        'all_items'                => 'Alle Arrangementer',
        'archives'                 => 'Arrangement Arkiver',
        'attributes'               => 'Arrangement Attributes',
        'insert_into_item'         => 'Insert into Arrangement', 
        'uploaded_to_this_item'    => 'Uploaded til denne Arrangement',
        'featured_image'           => 'Udvalgt billede',
        'set_featured_image'       => 'Vælg udvalgt billede',
        'remove_featured_image'    => 'Fjern udvalgt billede',
        'use_featured_image'       => 'Brug som udvalgt billede',
        'filter_items_list'        => 'Filtrer Arrangement liste', 
        'items_list_navigation'    => 'Arrangement liste navigation',
        'items_list'               => 'Arrangement liste',
        'item_published'           => 'Arrangement offentliggjort',
        'item_published_privately' => 'Arrangement offentliggjort privat',
        'item_reverted_to_draft'   => 'Arrangement lavet om til kladde',
        'item_scheduled'           => 'Arrangement planlagt',
        'item_updated'             => 'Arrangement opdateret',
    );

    $args = array(
        'rewrite' => array('slug' => 'arrangementer'),
        'labels' => $labels,
        'description' => 'Arrangementer til Det Gamle Posthus.',
        'public' => true,
        'hierarchical' => false,
        'menu_position' => 7,
        'menu_icon' => 'dashicons-beer',
        'has_archive' => false,        
        'taxonomies' => array( 'category' ),
        'supports' => array(
            'title', 'editor', 'page-attributes', 'thumbnail'
        ),
        
        
    );
    register_post_type( 'event', $args); 

    if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
            'key' => 'group_5e7497fa34421',
            'title' => 'Arrangementer',
            'fields' => array(
                array(
                    'key' => 'tobenski_5e74990c5bb6c',
                    'label' => 'Dato',
                    'name' => 'dato',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'l j F Y',
                    'return_format' => 'l \d\e\n j. F Y',
                    'first_day' => 1,
                ),
                array(
                    'key' => 'tobenski_5e74997f5bb6e',
                    'label' => 'Start Tidspunkt',
                    'name' => 'start_tidspunkt',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H.i',
                    'return_format' => 'H.i',
                ),
                array(
                    'key' => 'tobenski_5e749b04aa8b3',
                    'label' => 'Slut Tidspunkt',
                    'name' => 'slut_tidspunkt',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H.i',
                    'return_format' => 'H.i',
                ),
                array(
                    'key' => 'tobenski_5e74992a5bb6d',
                    'label' => 'Dato som tekst',
                    'name' => 'dato_som_tekst',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Skriv Dato med tekst fx. "fredag den 3. marts"',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'tobenski_5e74987b27bd7',
                    'label' => 'Samlet Pris',
                    'name' => 'samlet_pris',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'tobenski_5e74988727bd8',
                    'label' => 'Reserver Link',
                    'name' => 'reserver_link',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'tobenski_5e7498a027bd9',
                    'label' => 'Reserver Text',
                    'name' => 'reserver_text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'tobenski_600358d662423',
                    'label' => 'Menu',
                    'name' => 'menu',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
                array(
                    'key' => 'tobenski_78957f1f5c3fb',
                    'label' => 'Events Secondary Image',
                    'name' => 'event_secondary_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'event',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));
        
        endif;
}
